### ISSUE TITLE
discussion of plugin validation and what lives in napari vs the plugin engine

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-plugin-engine#16]
following on from  https://github.com/napari/napari-plugin-engine/pull/15#issue-561931730 by @ziyangczi 

> we will allow people to run these checks in their CI/CD after the deployment step to check it is discoverable by napari

I want to address the idea of doing validation/ testing without depending on napari.

If the use case is primarily CI/ CD then I don't see being forced to depend on napari to do the test isn't that big a deal. I see a big difference between a plugin being forced to depend on napari to exist and be distributed - we don't want that - but I don't mind having to force someone to add napari to a testing environment to check that their plugin works with napari, that seems ok. In napari itself we have many packages in our testing environment that we don't have in our main environment, and napari will always be present in the environment when the package is being used as a napari plugin. We've also gone to great lengths to get napari to install well without qt, and possibly one day be truly headless without vispy too.

Even for people developing locally if they want to test napari plugin compatibility, it's not that unreasonable to force them to have napari installed for testing, as if they care about validation as a napari plugin they are probably able to install napari.

With respect to #15 I can see good reason why the plugin discovery code should live in the plugin engine and so am happy for that PR and a gradual migration, and we should probably try and test as much as possible without relying on napari, but there will be some things that won't make sense to duplicate.

For example right now the actual plugin interface (the hook specifications) are defined inside napari and I don't think we have any plans to move them in here anytime soon, though i could actually see one day how it might be nice as we could have our plugin interface versioned and released on a different timescale than napari itself. Coordinating the development across the repos would be a pain, but it might yield nice benefits long term.

cc @tlambert03 @jni

**Comment by tlambert03** [comment]
> With respect to #15 I can see good reason why the plugin discovery code should live in the plugin engine

... _sort_ of.  but the plugin engine doesn't use this code (and probably won't ever).  This is pretty much _only_ for "internet" searching of plugins, which we do in the napari plugin gui to facilitate plugin installation.

> If the use case is primarily CI/ CD then I don't see being forced to depend on napari to do the test isn't that big a deal.

definitely agree with this

> check it is discoverable by napari

We could basically test this for them just by grepping "Framework :: napari" in their `setup.py` or `setup.cfg`.  This feels like one of those things where you don't need to duplicate the tests of your "dependencies", and in this case PyPI is the dependency, and I trust that if someone puts the framework `Framework :: napari` classifier in there, then PyPI probably will probably get the job done.

**Comment by ziyangczi** [comment]
adding what I am hearing from the plugin developers, I agree that the benefit of excluding napari as a dependency in CI/CD may be negligible, overall the benefit comes from allowing developers to have a different development cycle aside from napari roadmap, and save them from the trouble of knowing what is happening in napari all the time. I believe there will be a point where we feel more comfortable having all the specifications living in here than the core (I don't think now is the time), and at that point, the code would mostly freeze in the plugin engine, so that core and plugins can go separate ways in their own direction without having to worry too much about each other.

on the pypi classifier, I agree that the best-case scenario only needs a simple test, these tools would be necessary for those outliers, we need to be ready to support more general matching than just pypi classifier, be it existing distributions that have policy/sanitary issue not accomodating classifier, or even some of the plugins in the future may not even be able to distribute via pypi for whatever reason. I believe there is value in giving people these tools so they know exactly what is expected, and we can evolve our discovery method when we need to. (Plus we can grow the number of things that can be pre-checked as well, for example the dependency conflict check is a big win)

**Comment by tlambert03** [comment]
> or even some of the plugins in the future may not even be able to distribute via pypi for whatever reason

as I mentioned in the google doc... while it is certainly possible for someone to distribute a package outside of PyPI, it is unclear if/when we will be able to install it inside the bundle using the GUI installer (i.e. they're basically on their own at that point). so these hypotheticals are all well and good, but it feels to me like we're talking about moving and modifying actively used code here, for things that feel at best a long way off.

**Comment by sofroniewn** [comment]
> We could basically test this for them just by grepping "Framework :: napari" and "entry_points = 'napari.plugin'" in their setup.py or setup.cfg. This feels like one of those things where you don't need to duplicate the tests of your "dependencies", and in this case PyPI is the dependency, and I trust that if someone puts the framework Framework :: napari classifier in there, then PyPI probably will probably get the job done.

I love this idea, it seems very minimal and immediately useful. I know that my `napari-console` repo would pass as I manually added it, but my `napari-animation` repo would fail because I havn't. It's also the sort of test where a very clear error message could be given - please add "Framework :: napari" and/ or the entry point.

Maybe an idea for a first minimal working validation service would be a github action that simply looks to see if the framework classifier is there and the entry point is there. If you got that working @ziyangczi we could then build out more from there.

**Comment by tlambert03** [comment]
+1.  I think GitHub actions will be super useful
